imports:
    - { resource: services.yml }

# Temporary fix for making labels appear on top of each other
# Rowan: Commenting this fix out here since we wont always
# have mopa bootstrap implemented in our projects.  This fix
# should be applied on a project by project basis
#mopa_bootstrap:
#    form:
#      horizontal_label_class: control-label
#      horizontal_label_offset_class:  ~
#      horizontal_input_wrapper_class: ~
 
#Rowan: Only include this if necessary     
#twig:
#    form:
#        resources:
#            - 'SideclickCoreBundle:Form:fields.html.twig'
 
# Rowan: Lets not presume that the Liip Imagine Bundle is installed           
#liip_imagine:
#    filter_sets:
#        thumb_inset_200x200:
#            filters:
#                thumbnail: { size: [200, 200], mode: inset }
